- name: Garantindo a instalacao do epel-release
  yum:
    name: epel-release
    state: present

- name: Garantindo a instalacao do Nginx
  yum:
    name: nginx
    state: latest
  notify:
    - habilitando o nginx

- name: Copiando o arquivo nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Criando o diretorio conf.d
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: 0755

- name: Copiando o template do location para o servidor
  template:
    src: location.j2
    dest: /etc/nginx/conf.d/location.conf
    mode: 0644
  notify: 
    - iniciando o nginx